export const SPLIT_SIZE_MIN = 50
export const SPLIT_SIZE_MAX = 200
export const MAX_COMPLETION_TOKENS_MIN = 1024
export const MAX_COMPLETION_TOKENS_MAX = 164000
export const TEMPERATURE_MIN = 0.0
export const TEMPERATURE_MAX = 1.5
export const MAX_BATCH_CONCURRENT_OPERATION = 5
